[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd thesis-frontend && npm ci"]

[phases.build]
cmds = ["cd thesis-frontend && npm run build:production"]

[start]
cmd = "cd thesis-frontend && npx serve -s dist -l tcp://0.0.0.0:${PORT:-3000}"
